# Generated by Django 5.0.6 on 2024-09-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razao_Social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('Nome_Fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('Inscricao_Municipal', models.CharField(max_length=100, verbose_name='Inscrição Municipal')),
                ('Inscricao_Estadual', models.CharField(max_length=100, verbose_name='Inscrição Estadual')),
                ('UF', models.CharField(max_length=2, verbose_name='UF')),
                ('Cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('Bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('Logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('Numero', models.IntegerField(verbose_name='Número')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['Razao_Social'],
            },
        ),
    ]
