# Generated by Django 5.0.6 on 2024-09-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisicao', models.CharField(max_length=7, verbose_name='Nº Requisição')),
                ('data', models.DateField(verbose_name='Data')),
                ('documento', models.FileField(upload_to='Requisições/%Y/%d-%m-%Y/', verbose_name='Requisição')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituicao.instituicao')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-data'],
            },
        ),
    ]
