# Generated by Django 5.0.6 on 2024-09-09 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('instituicao', '0001_initial'),
        ('produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nf', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nota Fiscal')),
                ('modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade')),
                ('requisicao', models.CharField(blank=True, max_length=7, null=True, verbose_name='Nº Requisição')),
                ('movimento', models.CharField(blank=True, choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1, verbose_name='Movimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('semana', models.CharField(blank=True, max_length=15, null=True, verbose_name='Semana')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedor.fornecedor')),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituicao.instituicao')),
            ],
            options={
                'verbose_name': 'Estoque',
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='EstoqueEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'Estoque de Entrada',
                'verbose_name_plural': 'Estoque de Entradas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoques.estoque',),
        ),
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
            ],
            options={
                'verbose_name': 'Estoque de Saída',
                'verbose_name_plural': 'Estoque de Saídas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('estoques.estoque',),
        ),
        migrations.CreateModel(
            name='EstoqueItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço Unitário')),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Preço Total')),
                ('quantidade_req', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Requerida')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField(blank=True, verbose_name='Saldo em Estoque')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoques.estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Estoque Itens',
                'ordering': ('pk',),
            },
        ),
    ]
