# Generated by Django 5.0.6 on 2024-09-09 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
                ('estoque', models.FloatField(verbose_name='Estoque Atual')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('un_medida', models.CharField(choices=[('kg', 'kg'), ('hg', 'hg'), ('dag', 'dag'), ('g', 'g'), ('dg', 'dg'), ('cg', 'cg'), ('mg', 'mg'), ('kl', 'kl'), ('hl', 'hl'), ('dal', 'dal'), ('l', 'l'), ('dl', 'dl'), ('cl', 'cl'), ('ml', 'ml'), ('mil', 'mil'), ('cx', 'cx'), ('dz', 'dz'), ('fd', 'fd'), ('sc', 'sc'), ('und.', 'und.')], default='kg', max_length=4, verbose_name='Unidade de Medida')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['produto'],
            },
        ),
    ]
